# This workflow will upload a Python Package using Twine when a the test-pypi branch is modified
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package to Test PyPi

# uncomment the following to upload to Test PyPi
# on:
#   workflow_run: 
#     workflows: ["build tag"]
#     # branches: [main] 
#     types:
#       - completed
on:
  push:
    branches: [ test-pypi ]
  pull_request:
    branches: [ test-pypi ]


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine


    
    # Upload to TestPyPI
    - name: Build and Upload to TestPyPI
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi

    # - name: Build and publish
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     python setup.py sdist bdist_wheel
    #     twine upload dist/*